import { prisma } from './prisma';

/**
 * Checks if an idempotency key exists, and if not, creates it.
 * This ensures that a request with a given key is processed exactly once.
 * 
 * @param idempotencyKey The unique key generated by the client
 * @returns true if the request was already processed, false if this is the first time
 */
export async function checkAndSetIdempotency(idempotencyKey?: string | null): Promise<boolean> {
  if (!idempotencyKey) return false;

  try {
    // Try to create the record. If it already exists, this will throw an error due to the unique @id constraint.
    await prisma.idempotencyRecord.create({
      data: {
        key: idempotencyKey,
      },
    });
    // Successfully created -> first time seeing this key
    return false;
  } catch (error: unknown) {
    // Prisma code for unique constraint violation is P2002
    const prismaError = error as { code?: string };
    if (prismaError.code === 'P2002') {
      console.warn(`Idempotency key ${idempotencyKey} already processed. Skipping duplicate execution.`);
      return true; // Already processed
    }
    // For other DB errors, allow the request to proceed (best effort)
    console.error('Error checking idempotency key:', error);
    return false;
  }
}
